
package com.sdcloud.webservices.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "erpWebServicesImpl", targetNamespace = "http://services.webservices.sdcloud.com/", wsdlLocation = "http://dev.cloudsmaker.net:9020/webservices/services/erp?wsdl")
public class ErpWebServicesImpl_Service
    extends Service
{

    private final static URL ERPWEBSERVICESIMPL_WSDL_LOCATION;
    private final static WebServiceException ERPWEBSERVICESIMPL_EXCEPTION;
    private final static QName ERPWEBSERVICESIMPL_QNAME = new QName("http://services.webservices.sdcloud.com/", "erpWebServicesImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dev.cloudsmaker.net:9020/webservices/services/erp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERPWEBSERVICESIMPL_WSDL_LOCATION = url;
        ERPWEBSERVICESIMPL_EXCEPTION = e;
    }

    public ErpWebServicesImpl_Service() {
        super(__getWsdlLocation(), ERPWEBSERVICESIMPL_QNAME);
    }

    public ErpWebServicesImpl_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ERPWEBSERVICESIMPL_QNAME, features);
    }

    public ErpWebServicesImpl_Service(URL wsdlLocation) {
        super(wsdlLocation, ERPWEBSERVICESIMPL_QNAME);
    }

    public ErpWebServicesImpl_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ERPWEBSERVICESIMPL_QNAME, features);
    }

    public ErpWebServicesImpl_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ErpWebServicesImpl_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ErpWebServicesImpl
     */
    @WebEndpoint(name = "ErpWebServicesImplPort")
    public ErpWebServicesImpl getErpWebServicesImplPort() {
        return super.getPort(new QName("http://services.webservices.sdcloud.com/", "ErpWebServicesImplPort"), ErpWebServicesImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ErpWebServicesImpl
     */
    @WebEndpoint(name = "ErpWebServicesImplPort")
    public ErpWebServicesImpl getErpWebServicesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.webservices.sdcloud.com/", "ErpWebServicesImplPort"), ErpWebServicesImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ERPWEBSERVICESIMPL_EXCEPTION!= null) {
            throw ERPWEBSERVICESIMPL_EXCEPTION;
        }
        return ERPWEBSERVICESIMPL_WSDL_LOCATION;
    }

}
