
package com.sdcloud.webservices.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ErpWebServicesImpl", targetNamespace = "http://services.webservices.sdcloud.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ErpWebServicesImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doServices", targetNamespace = "http://services.webservices.sdcloud.com/", className = "com.sdcloud.webservices.services.DoServices")
    @ResponseWrapper(localName = "doServicesResponse", targetNamespace = "http://services.webservices.sdcloud.com/", className = "com.sdcloud.webservices.services.DoServicesResponse")
    public String doServices(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

}
